### ISSUE TITLE
Option to pause or reset using the preview feature

### ISSUE THREAD

**Issue by DeysonOrtiz** [johndyer/mediaelement-plugins#11]
Hello and good day.

Right now the preview feature resets the video to the start when the mouse hovers out.  Is it possible to have an option to pause?  After testing I can see how some visitors may want to start off where they left off when they hover back on a video to play.  With it being optional we can test to see what is best.  

Thank you and have an amazing day! :)

**Comment by ron666** [comment]
It can be set but I'll let you know when ready. Thanks

**Comment by DeysonOrtiz** [comment]
Thank you!! :)

**Comment by ron666** [comment]
Please download the latest version from here and you will see a new element named `pauseOnlyOnPreview` and is set to false; if you set it to true then you will pause rather than reset. Thanks

**Comment by DeysonOrtiz** [comment]
Hello.  If I am using a cloud JS library do I need to download when you update?
I am using this:  <script src="https://cdn.jsdelivr.net/mediaelement-plugins/1.1.0/preview/preview.js"></script>

Thank you :)

**Comment by ron666** [comment]
Yeah you can't use CDN until I release the next version. You'll need to download. Once I figure out the issue with the preview audio completely (which I'm close) I'll bump the version number

**Comment by DeysonOrtiz** [comment]
Got it!  I will test it first thing in the morning!  Thank you good sir for all you awesomeness magic!  Have an amazing night! :)

**Comment by DeysonOrtiz** [comment]
Hello and good day.
I have downloaded both the preview and the player for testing.  

However, when I use the new player the video poster show up for a second and then they all hide and show the video player alone:  https://mmt.staging.wpengine.com/test-home/

When I switch back to the older player the video posters work as they should.  Please let me know what you think.  Thank you and have an amazing day! :)

**Comment by ron666** [comment]
Can you post the code you used for the poster, please? The fix had nothing to do with the player as a whole, just a matter of an event being fired out of time

**Comment by DeysonOrtiz** [comment]
I am using WordPress so I am using variables to call the posters and the videos:
One thing to point out is that it works with the older media player.

<video id="<?php the_ID(); ?>" width="568" height="319" poster="<?php echo ''.$tumbnail_uri.''; ?>" preload="none">
                    <source src="<?php echo ''.$url.''; ?>" type="video/vimeo">
                </video>

Please let me know what you think.  Thank you :)

**Comment by DeysonOrtiz** [comment]
Here is the same setup but using the older video player on this page:  https://mmt.staging.wpengine.com/

This is the one using the new player:
https://mmt.staging.wpengine.com/test-home/

Thank you :)

**Comment by ron666** [comment]
I have checked the difference but I cannot find anything related. One thing I do saw is that in your test environment is a delay when loading the poster images. I don't know if you can investigate this a little bit more please

**Comment by DeysonOrtiz** [comment]
I am sorry but I do not know of the delay you refer to.  
Here is the same test page but instead with the previous live version of the player loading from the CDN:  https://mmt.staging.wpengine.com/test-home/

`This is the player's CDN source that works: https://cdn.jsdelivr.net/mediaelement/3.1.2/mediaelement-and-player.js
`
Please let me know your feedback and if there is anything I can do to help.  Thank you :)

**Comment by ron666** [comment]
For the fix you will need to use a local version of mediaelement, not the CDN one, since the local version will carry the fixes

**Comment by DeysonOrtiz** [comment]
I am sorry for the misunderstanding.  I switched to the CDN just recently to demonstrate how the CDN version shows the video poster as intended.  

I have switched back to the local version as you have instructed and the video posters are missing as before.  The weird thing is that I see them appear for a second and then they disappear.   

Please let me know what you need me to do next.  I will be standing by.  Thank you :)

**Comment by ron666** [comment]
Totally weird. Just for testing purposes, can you put the latest libraries in the https://mmt.staging.wpengine.com/ just to make sure nothing is different between one and the other, please?

**Comment by DeysonOrtiz** [comment]
Yes.  Please stand by.

**Comment by DeysonOrtiz** [comment]
Done.  Video posters are not showing.  I agree that is it weird.  Please let me know what else you would like me to test.  Thank you :)

**Comment by ron666** [comment]
Can you send me the code you are using to show/hide poster images, please?

**Comment by DeysonOrtiz** [comment]
Yes sir:

```
$('video').mediaelementplayer({ 
    features: ['preview'],
    stretching: 'auto',
    muteOnPreviewMode: false,
    previewMode: true,
    fadeInAudioStart:0,
    fadeInAudioInterval:20,
    fadePercent: 0.04,
    delayPreview: 1000,
    pauseOnlyOnPreview: true,
    hideVideoControlsOnLoad: true,
    hideVideoControlsOnPause: true,
    showPosterWhenEnded: true,
    enableProgressTooltip: false,
    showPosterWhenPaused: true,
    
    controlsTimeoutMouseEnter: 750,
    clickToPlayPause: false,
    

});

```

**Comment by ron666** [comment]
Nothing here as far as I can see. I'm confused about this. I'll try to check some more. I'll keep you posted

**Comment by ron666** [comment]
If you wanna revert your libraries I'm fine with it, but leave the test site with the current ones so I can try to check the difference

**Comment by DeysonOrtiz** [comment]
I will leave everything as is until you tell me otherwise.  Thank you for your patience.  :)

**Comment by ron666** [comment]
After I updated the Preview plugin, I give it a try using a single video and I got everything right. I don't know if it's a loading time or what. I'm using the latest version of MEJS and the latest of the Preview plugin.

**Comment by DeysonOrtiz** [comment]
Hello.  I will download both the media player and preview plugin to test them out.  Thank you very much and I shall keep you posted.  :)

**Comment by DeysonOrtiz** [comment]
The video posters are showing!  Woo Hoo!  Thank you very much for all your amazing work! :)
You are awesome! :)

https://mmt.staging.wpengine.com/

**Comment by ron666** [comment]
I'm glad it's fixed! Have a nice weekend

**Comment by DeysonOrtiz** [comment]
You too! :)
