### ISSUE TITLE
Audio fade in jittery

### ISSUE THREAD

**Issue by DeysonOrtiz** [johndyer/mediaelement-plugins#13]
Hello and good day.  I am not sure if this is a limitation with Vimeo.  When I use the fade in controls, it seems to bounce up and down as the audio fades in.  You may see and hear it here.  https://mmt.staging.wpengine.com/

Here are the settings:  
    fadeInAudioStart:0,
    fadeInAudioInterval:20,
    fadePercent: 0.04,

Please let me know what you think.  Thank you for all your genius hard work! :)

**Comment by ron666** [comment]
You are welcome :) I'll check this and keep you posted

**Comment by DeysonOrtiz** [comment]
Thank you very much! :)

**Comment by ron666** [comment]
@DeysonOrtiz I pushed a new release and this issue is fixed on that new release. Check the CDN to get the latest version, and let me know how it worked for you. Thanks

**Comment by ron666** [comment]
Also, make sure you use the latest version (from GitHub) of the player; I fixed an issue related to Vimeo and this fix will be released on Thursday. Thanks

**Comment by DeysonOrtiz** [comment]
It works perfectly!  Thank you!  Future visitor's ears will thank you.  Have an amazing day! :)
