### ISSUE TITLE
Keep video playing while hover bottom div.

### ISSUE THREAD

**Issue by DeysonOrtiz** [johndyer/mediaelement-plugins#14]
Hello and good day.  I am using the Preview Plugin and I had wanted to know if there is a way to keep the video playing when a user hovers over the div underneath the video ( where the title and buy button are ):  https://mmt.staging.wpengine.com/

Thank you and have an amazing day! :)

**Comment by ron666** [comment]
You may need to create custom Javascript to trigger this, since the DIV is not part of the player. Something like this:
```javascript
$('YOUR DIV').hover(function() {
     // This is when user hovers in
     var id = $(this).closest('.cbp-caption').find('.mejs__container').attr('id');
     mejs.players[id].play();
}, function() {
     // This is when user hovers out
     var id = $(this).closest('.cbp-caption').find('.mejs__container').attr('id');
     mejs.players[id].pause();
});
```
