### ISSUE TITLE
Disable preview on scroll

### ISSUE THREAD

**Issue by DeysonOrtiz** [johndyer/mediaelement-plugins#15]
Hello and good day!  :)

Someone had just made a request to disable hover to preview feature while the user is scrolling the page.  Is this a possible option?  Thank you! :)

**Comment by ron666** [comment]
It might be complicated to do this, but I'll check if it's feasible

**Comment by DeysonOrtiz** [comment]
Thank you.  You are awesome! :)

**Comment by ron666** [comment]
Please download the latest version and, if you scroll, media will be paused automatically to avoid any misbehaviors. Thanks

**Comment by DeysonOrtiz** [comment]
This is working.  Thank you :)  Great work good sir! :)
