### ISSUE TITLE
Delay on Hover to Preview

### ISSUE THREAD

**Issue by DeysonOrtiz** [johndyer/mediaelement-plugins#16]
Hello and good day! :)

If it is not too much trouble, is it possible to add an option to have a delay before the hover to preview begins?   This way if a person is moving their cursor over a few thumbnails to get to one they do not all get triggered.  

Please let me know what you think and have an amazing day! :)

**Comment by ron666** [comment]
Please download the latest version and you can use now a `delayPreview` element, in which you can set in milliseconds the delay to start playing media. Thanks

**Comment by DeysonOrtiz** [comment]
Hello and good day.  

I think you are close good sir.  However, I just wanted to let you know that when someone goes over a video to go somewhere else the video begins to play even the mouse is not on that video anymore.

Here is a quick video to illustrate what I mean:  http://quick.as/Lq4iZb9x

Thank you again for all your hard work!  Thank you and have an amazing day! :)

**Comment by ron666** [comment]
Can you download the latest version and check this now, please? I think I missed to clear a variable to avoid this behavior. Keep me posted and thanks for testing this.

**Comment by DeysonOrtiz** [comment]
I will check right now.  Thank you :)

**Comment by ron666** [comment]
Can you send me your URL to check this please?

**Comment by DeysonOrtiz** [comment]
I have switched the player to the previous player for a test in another of our conversations.  However, the preview plugin is the new one:  https://mmt.staging.wpengine.com/test-home/

Thank you very much for your help.  I look forward to your response.  :)

**Comment by ron666** [comment]
Ok please download the latest version of the plugins; I figured out why it wasn't responding properly. Let me know and thanks for reporting this

**Comment by DeysonOrtiz** [comment]
Brilliant work my friend!  You are a rockstar in coding and development!  :)
Thank you very much for all your hard work! :)

P.S. would it be too much trouble if we could have a loading animation occur during the delay?  This way the users know something is about to play. Please let me know what you think. 

 Have a wonderful day!

**Comment by ron666** [comment]
You mean like the loading animation?

**Comment by DeysonOrtiz** [comment]
Yes, a spinner of sorts.  I believe MediaElements player has one.  I had thought when a user hovers the loading animation appears during the delay and hides when the video plays.  What do you think?

**Comment by ron666** [comment]
It could be. Let me see and I'll let you during the course of the day.

**Comment by DeysonOrtiz** [comment]
Thank you very much! I look forward to your response.  :)

**Comment by ron666** [comment]
Ok download the latest version of the plugin and let me know. Thanks

**Comment by DeysonOrtiz** [comment]
That is beautiful!  I love it!   You are a genius, my friend!  :)   Wow!!!  Thank you very much for you sharing your expertise, you are brilliant. :)

https://mmt.staging.wpengine.com/

**Comment by ron666** [comment]
You are welcome. Thanks for being on top of this plugin. Just for curiosity, do you speak Spanish?

**Comment by DeysonOrtiz** [comment]
You are very welcome, I am happy to help.  Si señor, hablo español.  :)

**Comment by ron666** [comment]
perfecto, cuando necesites algo mas avísame. Ten un excelente fin de semana!

**Comment by DeysonOrtiz** [comment]
Muchas gracias! 
Estoy bien agradecido por todo la ayuda que uste mi ha dado. 
Gracias y tenga un bellisimo dia!  :)

**Comment by ron666** [comment]
Igualmente ten un excelente dia :)

**Comment by DeysonOrtiz** [comment]
Gracias! :)
