### ISSUE TITLE
what does the other configuration mean?

### ISSUE THREAD

**Issue by chaserstrong** [johndyer/mediaelement-plugins#17]
In the wiki, just like below, where can i find the details of configuration?
`    $('video').mediaelementplayer({
        defaultSpeed: 0.75,
        // other configuration elements
    });`

**Comment by ron666** [comment]
Check the documents of each plugin here if you use any of them; otherwise, check [here](https://github.com/johndyer/mediaelement/blob/master/docs/api.md) for more info

**Comment by chaserstrong** [comment]
@ron666  I got it, thanks very much.
