### ISSUE TITLE
Hover effect on videos.  

### ISSUE THREAD

**Issue by DeysonOrtiz** [johndyer/mediaelement-plugins#7]
I have a request for videos that autoplay on hover.  Options could be to return the image when a user hovers off the image, to reset the video or simply pause the video so it starts where it was left off.

Please watch the hover effect on thumbnails to see what I mean: https://pixabay.com/en/videos/list/?q=dance&image_type=video&cat=&min_width=&min_height=

Thank you for all your hard work and have an amazing day!

**Comment by DeysonOrtiz** [comment]
Update: The show image on pause has been added.  The one thing needed for this feature request is to play video on mouse hover.   

Thank you :)

**Comment by ron666** [comment]
@DeysonOrtiz Please download the latest version of the player and test `previewMode: true` configuration; if you need to add sound to the preview, just use `muteOnPreviewMode: false`. Let me know if that works for you.

**Comment by DeysonOrtiz** [comment]
WOW!  Thank you so much! 
Great idea on muting the Audio option.  Another option I have seen used for Mouse Over Video Ads is an audio fade-in when the video starts to play, so people will not be shocked by the audio.

Is this possible to do in the ME player?  

Thank you for all your brilliant work!  You, my friend, are a rock star! :)

**Comment by ron666** [comment]
Thanks man :) if you can point an example of the audio fade in I can take a look and check if it can be integrated

**Comment by DeysonOrtiz** [comment]
Great minds think alike.  I was just about to look for some examples.  I did come across a topic:  http://stackoverflow.com/questions/7451508/html5-audio-playback-with-fade-in-and-fade-out/13149848

I will search for the examples I have seen. They had an Audio Fade In and I believe also a Fade Out.

Thank you! :)

**Comment by DeysonOrtiz** [comment]
Would this help?  http://www.jqueryscript.net/other/jQuery-Plugin-for-Fade-in-Fade-out-HTML5-Audio-fadeaudio.html

Also, maybe instead of True or False, we can add a time to the fade in or out.  0 = no fade and 1+ seconds fade.  What do you think?

**Comment by ron666** [comment]
Sounds interesting. Let me see what I can get to achieve this once I review those 2 links you provided me. Thanks

**Comment by DeysonOrtiz** [comment]
Great!  Please let me know if you need me to find some more for you.    Thank you, good sir! :)

**Comment by ron666** [comment]
Please download the latest version of the plugin and use the following config elements so you can achieve the whole behavior of playing when hovering and fading in/out at a certain point of the media:
```javascript
$('video').mediaelementplayer({
                previewMode: true,
		muteOnPreviewMode: false,
		fadeInAudioInterval: 200,
		// If fade in set in, time when it starts fading in
		fadeInAudioStart: 0,
		// When playing media, fade out audio (fade in must be greater than zero)
		fadeOutAudioInterval: 200,
		// If fade in set in, time when it starts fading in
		fadeOutAudioStart: 15,
		// Percentage in which media will fade in/out (in decimals, where 0.2 = 20%, 1 = 100%)
		fadePercent: 0.02
});
```
Let me know if that works for you. Thanks

**Comment by DeysonOrtiz** [comment]
Woo Hoo!!!!!! Thank you! It works beautifully!  Great work, you are a genius, my friend! :)

However, I did find one issue or bug, I do not know if it was there before or if it is new. But, when we hover to play the video and while it is playing if we hover over the bottom controls, the video stops and resets and does not play again unless we hover off and on again.  Did I do something wrong, or is this in the player.  Thank you. :)

https://mmt.staging.wpengine.com/testing-dual-header/

**Comment by DeysonOrtiz** [comment]
One more thing, I have never downloaded the MediaElements Plugins.  Is that different?  Where do I install this?  Thank you. :)

**Comment by ron666** [comment]
Yeah I may need to check that issue; just download the repo and use whatever plugins you need after the mediaelement script; in your case, check first the plugins available in the README file to make sure you need to install any of them or not

**Comment by DeysonOrtiz** [comment]
I do not see this feature in the plugins.  So I guess you had added it to the core.  :)

**Comment by ron666** [comment]
Yeah correct

**Comment by DeysonOrtiz** [comment]
Ok great!  Thank you.  :)

**Comment by ron666** [comment]
You know what? I should actually put this as a plugin. So I'm working on that plus giving a nice solution for the bug you indicated. In order to install any plugin, you download the repo and reference the plugin you want like this (in your case, the name of the feature would be `preview`):
```html
<script src="/path/to/mediaelement-and-player.js"></script>
<script src="/path/to/preview/preview.js"></script>
<script>
$('video').mediaelementplayer({ 
                // configuration for your plugin
                features: ['playpause', 'current', 'progress', 'duration', 'volume', 'preview'],
                previewMode: true,
		muteOnPreviewMode: false,
		fadeInAudioInterval: 200,
		fadeInAudioStart: 0,
		fadeOutAudioInterval: 200,
		fadeOutAudioStart: 15,
		fadePercent: 0.02
});
</script>
```
I'll let you know when it's ready :)

**Comment by ron666** [comment]
@DeysonOrtiz Ok it's ready just follow the instructions I described in the previous comment, or check the README.

**Comment by ron666** [comment]
Also download the latest version of the player to svoid any conflicts

**Comment by DeysonOrtiz** [comment]
Thank you.  I will try it out right now! :)

**Comment by DeysonOrtiz** [comment]
@ron666 It seems that the play on hover does not work now.  Here is the test site:  https://mmt.staging.wpengine.com/testing-dual-header/

Please let me know what you think.  Thank you and have a beautiful day! :)

**Comment by ron666** [comment]
It doesn't work because you haven't added the item in your `features` list; should be:
```javascript
features: ['progress', 'volume', 'fullscreen', 'preview'],
```

**Comment by DeysonOrtiz** [comment]
Oh ok, I get it.  I had wanted to the same look and had copied the old feature layout.  I am very sorry for missing the new preview feature.   Works it perfect now!  Thank you :)

One thing you may want to let users know is that the video leaks through a very little bit of the audio before the audio fade in kicks in.  I do not know if this is a limitation on HTML5 video/audio.  However, it is much better now than having the audio blast on start and scare people out of their seats.  :)

Thank you for all your wonderful help and have an amazing day good sir! :)

**Comment by ron666** [comment]
Thank you! Closing this issue now

**Comment by veliis** [comment]
hello i can do how i want to make such a work on my wordpress site
