### ISSUE TITLE
New preview mode allow clickable video.

### ISSUE THREAD

**Issue by DeysonOrtiz** [johndyer/mediaelement-plugins#9]
Hello and good day.

I had wanted to know.  Now that there is a hover to play preview mode, can the video itself be clicked on to send a visitor to another page?

Thank you and have an amazing day! :)

**Comment by ron666** [comment]
It can but you may need to use the `success` method to do it:
```javascript
$('video').mediaelementplayer({
     // previous configuration
     clickToPlayPause: false,
     success: function(media, node) {
           $(node).closest('.mejs__container').on('click', function() {
                  window.location = "[your URL]";
           });
     }
})
```
Let me know if that works for you.

**Comment by DeysonOrtiz** [comment]
Hello and good day!  I hope you are not tired of me yet. :)

Do we add this to the demo.js or add it under the HTML5 code?  Thank you :)

**Comment by DeysonOrtiz** [comment]
I got it.  I added to the Demo.js.  Thank you! :)

**Comment by ron666** [comment]
You are welcome :)

**Comment by DeysonOrtiz** [comment]
Out of curiosity.  Can I add this script under the video HTML instead of Demo.js?  The reason is I need to pass a variable into it.  Can I use both inline and demo.js at the same time?  Thank you :)

**Comment by ron666** [comment]
Yes you can, just check the order of your scripts to make sure you don't have any errors between the inline JS and the demo.js

**Comment by DeysonOrtiz** [comment]
Ok.  Thank you :)


-- ---

Deyson Ortiz
deyson.com + motionmastertemplates.com
